// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.euchre.ui.tutorial

import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Seat
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.cardkit.ui.tutorial.TutorialPage

/**
 * LESSON 4 — defending. The dealer picks the turn card up on a thin hand and the human's side
 * breaks her: three tricks to the defence is a EUCHRE, worth 2 points.
 *
 * The exact trace of seed 938 with Fen (seat 3) dealing, every house rule off — generated by
 * `ai/src/jvmTest/.../TutorialTraceGenerator.kt`:
 *
 *   Bots: seat 1 = Hugo, seat 2 = Dara (your partner), seat 3 = Fen (dealer)
 *   Turn card 10♥ · you, Hugo and Dara pass · Fen orders it up for herself, buries K♠ · trump ♥
 *   Your hand: K♦ K♥ 9♥ 10♦ A♦
 *   1: YOU A♦ · Hugo 9♦ · Dara Q♦ · Fen 10♥   -> Fen (ruff)
 *   2: Fen A♥ · YOU 9♥ · Hugo 9♣ · Dara J♦    -> Dara (left bower over the ace)
 *   3: Dara A♠ · Fen Q♥ · YOU K♥ · Hugo J♠    -> you (over-ruff)
 *   4: YOU K♦ · Hugo 10♣ · Dara Q♠ · Fen Q♣   -> you
 *   5: YOU 10♦ · Hugo J♣ · Dara K♣ · Fen A♣   -> you
 *   Makers took 1 of 5: euchred, +2 to your side.
 *
 * Do not edit a line of the prose without checking it against that trace.
 */
internal fun defenseLesson(): TutorialLesson = TutorialLesson(
    id = "defense",
    ordinal = 4,
    title = "Defending",
    subtitle = "Let them overreach, then euchre them",
    seed = 938L,
    dealer = Seat(3),
    prologue = defensePrologue(),
    steps = defenseSteps(),
    trickNotes = defenseTrickNotes(),
    handDone = "The hand is done. See what euchring them was worth.",
    epilogue = defenseEpilogue(),
    completion = "You passed on a hand that could not call, kept the K♥ back instead of burning " +
        "it under an ace, over-ruffed the maker to take the lead and held Fen to a single trick: " +
        "euchred, +2. That is the last lesson — start a real game from the home screen.",
)

/**
 * The pages read before the hand is dealt.
 */
private fun defensePrologue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "The other half of the game",
        body = "Half of every Euchre game is played without the trump suit you would have " +
            "chosen. When the other side makes trump, your target is simple: take three of " +
            "the five tricks. Do it and they are EUCHRED — they score nothing and your side " +
            "takes 2 points, the same as a march.\n\n" +
            "That is why passing is not a defeat. A thin hand that makes trump is a hand " +
            "you can punish.",
    ),
    TutorialPage(
        title = "Two tools",
        body = "Defending well comes down to two habits.\n\n" +
            "Do not spend a high trump under a higher one. If the maker leads a card you " +
            "cannot beat, follow with your smallest and keep the good one for a trick it " +
            "can actually take.\n\n" +
            "And watch for the OVER-RUFF: when someone trumps a suit you are also out of, " +
            "you may trump it too — with a bigger trump. Taking a trick off the maker that " +
            "way is usually where a euchre comes from.",
    ),
)

/**
 * Every human decision of the lesson, in order. Grounded in the trace above — do not edit one
 * without the other.
 */
private fun defenseSteps(): List<EuchreTutorialStep> = listOf(
    EuchreTutorialStep.Round1Step(
        orderUp = false,
        advice = "You sit to the dealer's left, so the bidding starts with you. Ordering the " +
            "10♥ up would make hearts trump AND put that card in Fen's hand — and Fen is on " +
            "the other side. You hold K♥ and 9♥: two middling trumps, no bower, no ace. " +
            "That is not enough to call, and certainly not enough to help an opponent. Pass.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.ACE of Suit.DIAMONDS,
        advice = "Everyone passed — and then Fen ordered it up for herself, which after " +
            "three refusals means she is betting on a thin hand. Take three tricks and she " +
            "is euchred. You lead: start with your best plain-suit card, the A♦, and see " +
            "who is short of diamonds.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.NINE of Suit.HEARTS,
        advice = "Fen leads the A♥ — a trump, and you hold two, so you must follow with one " +
            "of them. You cannot beat an ace, so do not waste the King under it: throw the " +
            "9♥ and keep the K♥ for a trick it can win.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.KING of Suit.HEARTS,
        advice = "Here it is. Your partner Dara leads the A♠, Fen has no spades and trumps " +
            "it with the Q♥ — but you have no spades either, and your K♥ beats her Queen. " +
            "OVER-RUFF her and the trick is yours.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.KING of Suit.DIAMONDS,
        advice = "Count Fen's trumps: 10♥, A♥ and Q♥ have all been played, so she has none " +
            "left to ruff with. Your side has two tricks; one more euchres her. Lead the " +
            "K♦ — the ace is gone, so it is the best diamond in the game now.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.TEN of Suit.DIAMONDS,
        advice = "That is the euchre already banked. Lead your last card, the 10♦, and watch " +
            "what comes down on it — there is an ace among them, and it will not win a " +
            "thing, because clubs were neither led nor trump.",
    ),
)

/**
 * Shown while a completed trick is held on the felt, keyed by trick number 1-5. In practice only
 * the tricks a BOT wins are ever held (winning one puts the lead straight back in your hands);
 * the rest are safety notes.
 */
private fun defenseTrickNotes(): Map<Int, String> = mapOf(
    1 to "Fen was out of diamonds and trumped your ace with the 10♥. Leading an ace always " +
        "risks exactly that. Tap the trick to continue.",
    2 to "Fen's A♥ looked untouchable — until Dara dropped the J♦ on it. Hearts are trump, " +
        "so the Jack of the other RED suit is a heart: the LEFT BOWER, and it beats the " +
        "ace. One trick each. Tap the trick to continue.",
    3 to "Your K♥ over-ruffed Fen's Q♥. Two tricks to the defence, one to the makers, and " +
        "Fen has spent every trump she had.",
    4 to "Nothing left to ruff with, so the K♦ walked in. Three tricks: Fen is EUCHRED.",
    5 to "The A♣ took nothing — clubs were neither led nor trump. Four tricks to the " +
        "defence: the makers score nothing and your side takes 2.",
)

/**
 * The pages read after the hand has been scored.
 */
private fun defenseEpilogue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "That is the whole game",
        body = "Four hands in, you have seen everything Euchre asks of you: following suit, " +
            "the two bowers, making trump in either round, the dealer's discard, going " +
            "alone, and euchring the other side.\n\n" +
            "What is left is judgement — and that only comes from playing. Settings let you " +
            "add the common house rules (stick the dealer, defend alone, Benny, farmer's " +
            "hand) and turn the bots up to Advanced when the standard ones stop being a " +
            "problem.",
    ),
)
