// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.euchre.ui.tutorial

import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Seat
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.cardkit.ui.tutorial.TutorialPage

/**
 * LESSON 3 — going alone, and the dealer's discard. The human deals, the right bower is turned up,
 * they pick it up alone, bury the odd card and march for 4.
 *
 * The exact trace of seed 830 with the human (seat 0) dealing, every house rule off — generated by
 * `ai/src/jvmTest/.../TutorialTraceGenerator.kt`:
 *
 *   Bots: seat 1 = Cleo, seat 2 = Ada (your partner), seat 3 = Nils · YOU deal
 *   Turn card J♣ · Cleo, Ada, Nils pass · you order it up ALONE · trump ♣ · Ada sits out
 *   Your hand: J♠ Q♣ K♣ A♣ 9♥ + the J♣ picked up, 9♥ buried
 *   1: Cleo A♠ · Nils Q♠ · YOU Q♣   -> you (ruff)
 *   2: YOU J♣ · Cleo J♥ · Nils 9♦   -> you
 *   3: YOU J♠ · Cleo K♦ · Nils 10♦  -> you
 *   4: YOU A♣ · Cleo A♥ · Nils K♠   -> you
 *   5: YOU K♣ · Cleo A♦ · Nils K♥   -> you
 *   Five tricks alone: +4.
 *
 * Do not edit a line of the prose without checking it against that trace.
 */
internal fun aloneLesson(): TutorialLesson = TutorialLesson(
    id = "alone",
    ordinal = 3,
    title = "Going alone",
    subtitle = "Pick it up, bury a card, and play without your partner",
    seed = 830L,
    dealer = Seat(0),
    prologue = alonePrologue(),
    steps = aloneSteps(),
    trickNotes = aloneTrickNotes(),
    handDone = "Five for five, alone. See what that scored.",
    epilogue = aloneEpilogue(),
    completion = "You picked up the right bower, buried the one card that could not win, sent " +
        "your partner out of the hand and took all five tricks: +4. Last lesson: what to do when " +
        "the other side makes trump.",
)

/**
 * The pages read before the hand is dealt.
 */
private fun alonePrologue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "The dealer's privilege",
        body = "When the turned-up card is ordered up, the dealer takes it into hand — and " +
            "then holds six cards, so one must be buried face down. That discard is a real " +
            "decision: it is your chance to throw away a card that was never going to win, " +
            "and it never comes back.\n\n" +
            "You deal this hand, and the card sitting face up is a very good one indeed.",
    ),
    TutorialPage(
        title = "Alone",
        body = "Whoever makes trump may declare that they are going ALONE. Their partner " +
            "lays their cards down and sits the hand out, so it is one player against two.\n\n" +
            "The reward is steep: a lone hand that takes all five tricks scores 4 points " +
            "instead of 2 — nearly half the game in one hand. Take three or four and you " +
            "still score only 1, and being euchred still gives the other side 2. So it is a " +
            "bet, and you only take it on a hand that cannot lose.",
    ),
)

/**
 * Every human decision of the lesson, in order. Grounded in the trace above — do not edit one
 * without the other.
 */
private fun aloneSteps(): List<EuchreTutorialStep> = listOf(
    EuchreTutorialStep.Round1Step(
        orderUp = true,
        alone = true,
        advice = "Everyone passed, and look at what they passed on: the turn card is the " +
            "J♣ — the right bower if clubs are trump — and you are the dealer, so ordering " +
            "it up puts it in YOUR hand. That would give you J♣, J♠ (the left bower), A♣, " +
            "K♣ and Q♣: the five highest clubs in the deck. Nothing can beat them. Tick GO " +
            "ALONE, then pick it up.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.DiscardStep(
        card = Rank.NINE of Suit.HEARTS,
        advice = "Six cards, and you may keep only five, so one goes face down. Easy this " +
            "time: the 9♥ is your only card outside the trump suit and the weakest thing in " +
            "the deck. Burying it leaves you holding nothing but trumps — nobody can even " +
            "make you follow a suit. Tap the 9♥, then Discard.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.CLUBS,
        advice = "Ada has laid her cards down; it is you against Cleo and Nils. Cleo leads " +
            "the A♠ and you hold no spades — your J♠ is a club today — so you may play " +
            "anything, and any trump wins. Spend the cheapest one you have: the Q♣.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.JACK of Suit.CLUBS,
        advice = "Now simply run your trumps from the top and they can never get in. The " +
            "J♣ first: the right bower, the best card in the game.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.JACK of Suit.SPADES,
        advice = "The J♠ next — the left bower, and remember it is a club for this hand, " +
            "not a spade. Second-highest trump, so it cannot lose either.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.ACE of Suit.CLUBS,
        advice = "With both Jacks gone the A♣ is the best club left. Lead it: that is four " +
            "tricks, and the fifth is already yours.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.KING of Suit.CLUBS,
        advice = "The K♣ finishes it. Five tricks, alone, from a hand you built by picking " +
            "up one Jack.",
    ),
)

/**
 * Shown while a completed trick is held on the felt, keyed by trick number 1-5. In practice only
 * the tricks a BOT wins are ever held (winning one puts the lead straight back in your hands);
 * the rest are safety notes.
 */
private fun aloneTrickNotes(): Map<Int, String> = mapOf(
    1 to "Cleo led an ace and it fell to your smallest trump, because you had no spades to " +
        "follow with.",
    2 to "Neither of them had a club to follow with, so the right bower simply walked in.",
    3 to "The left bower took the third trick, and the discards have given it away: between " +
        "them Cleo and Nils do not hold a single trump.",
    4 to "That is the third trick, so the hand is safely made — and going alone means the " +
        "march is still live.",
    5 to "Five out of five, alone: 4 points, the biggest score in Euchre.",
)

/**
 * The pages read after the hand has been scored.
 */
private fun aloneEpilogue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "Was it worth it?",
        body = "Going alone with the same hand and taking only four tricks would have " +
            "scored 1, exactly as if your partner had played. The extra points only arrive " +
            "for all five, so the question to ask is never \"can I make it?\" but \"can " +
            "anything in the other two hands take a trick from me?\"\n\n" +
            "Holding the top trumps with no side suit to be led through is the clearest " +
            "yes there is. Two bowers and an ace with a weak side card is usually not.",
    ),
    TutorialPage(
        title = "About that discard",
        body = "The bury is worth thinking about even when it is not obvious. Throwing your " +
            "last card of a suit is often stronger than throwing your lowest card overall: " +
            "hold none of a suit and you can trump it when it is led, which turns a small " +
            "trump into a winner. Never bury a trump, and never bury a lone ace.",
    ),
)
