// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.euchre.ui.tutorial

import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Seat
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.cardkit.ui.tutorial.TutorialPage

/**
 * LESSON 1 — the basics. A bot makes trump and the human just plays, guided through all five
 * tricks: what trump is, why both black Jacks are spades when spades are trump, and that following
 * the led suit is compulsory.
 *
 * The exact trace of seed 3929 with Kira (seat 1) dealing, every house rule off and the standard
 * bots at seats 1–3 — generated by `ai/src/jvmTest/.../TutorialTraceGenerator.kt`:
 *
 *   Bots: seat 1 = Kira (dealer), seat 2 = Nils (your partner), seat 3 = Bruno
 *   Turn card 9♠ · Nils orders it up · Kira picks it up and buries 9♥ · trump ♠
 *   Your hand: 10♥ 9♣ J♠ Q♣ Q♦
 *   1: Nils J♣ · Bruno 10♠ · YOU J♠ · Kira 9♠            -> you
 *   2: YOU Q♣ · Kira A♣ · Nils Q♠ · Bruno K♣             -> Nils (ruff)
 *   3: Nils A♥ · Bruno J♥ · YOU 10♥ · Kira Q♥            -> Nils
 *   4: Nils 10♦ · Bruno J♦ · YOU Q♦ · Kira 10♣           -> you
 *   5: YOU 9♣ · Kira K♥ · Nils A♠ · Bruno 9♦             -> Nils
 *   All five tricks to your side: a march, +2.
 *
 * Do not edit a line of the prose without checking it against that trace.
 */
internal fun basicsLesson(): TutorialLesson = TutorialLesson(
    id = "basics",
    ordinal = 1,
    title = "Your first hand",
    subtitle = "Trump, the two Jacks, and following suit",
    seed = 3929L,
    dealer = Seat(1),
    prologue = basicsPrologue(),
    steps = basicsSteps(),
    trickNotes = basicsTrickNotes(),
    handDone = "That is all five tricks played. See how the hand scored.",
    epilogue = basicsEpilogue(),
    completion = "You followed suit when you had to, you saw the J♣ act as a spade and lose to " +
        "the J♠, and you watched your partner ruff a trick your side could not win outright. " +
        "Nils took all five: a march, +2. Next lesson: making trump yourself.",
)

/**
 * The pages read before the hand is dealt.
 */
private fun basicsPrologue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "Welcome to Euchre",
        body = "Euchre is a fast trick-taking game for four players in two fixed teams. Your " +
            "partner sits opposite you; the other two are against you. The deck is tiny — " +
            "just 9, 10, J, Q, K, A in each suit, 24 cards — and everyone is dealt five. " +
            "First side to 10 points wins the game.",
    ),
    TutorialPage(
        title = "What is a trick?",
        body = "A trick is one card from each player, played in turn around the table, and " +
            "the best card takes all four. Whoever wins a trick leads the next one. Five " +
            "cards each means every hand is a fight over exactly five tricks.\n\n" +
            "The one rule you must obey: if you hold a card of the suit that was led, you " +
            "have to play one. Only when you have none of it may you play whatever you like.",
    ),
    TutorialPage(
        title = "Trump, and the two Jacks",
        body = "Every hand has a trump suit, decided before play. Any trump beats any card " +
            "of any other suit, however high.\n\n" +
            "Then Euchre's famous twist: the Jack of the trump suit is the best card in the " +
            "game — the RIGHT BOWER. And the other Jack of the same COLOUR leaves its own " +
            "suit and becomes a trump too, ranking just below it — the LEFT BOWER. With ♠ " +
            "trump the order runs J♠, J♣, A♠, K♠, Q♠, 10♠, 9♠. The J♣ is a spade now: you " +
            "cannot play it on a club, and it beats every club anyway.",
    ),
    TutorialPage(
        title = "One hand, guided",
        body = "You will play a single hand against three bots with advice at every step, " +
            "and only the recommended card enabled — so you cannot go wrong. Somebody else " +
            "makes trump this time; all you have to do is play your five cards. Watch what " +
            "the Jacks do.",
    ),
)

/**
 * Every human decision of the lesson, in order. Grounded in the trace above — do not edit one
 * without the other.
 */
private fun basicsSteps(): List<EuchreTutorialStep> = listOf(
    EuchreTutorialStep.PlayStep(
        card = Rank.JACK of Suit.SPADES,
        advice = "Your partner Nils made ♠ trump, and he leads the J♣. That is not a club: " +
            "with spades trump the other black Jack IS a spade, the LEFT BOWER. So spades " +
            "were led, and you must follow with your only spade — which happens to be the " +
            "J♠, the RIGHT BOWER, the highest card in the game. Play it and take the trick.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.CLUBS,
        advice = "You won, so you lead. That J♠ was your only trump, so from here you are " +
            "leading plain suits: try the Q♣. The A♣ and K♣ are still out there, but Nils " +
            "made trump and still holds some — if he is out of clubs he can trump the trick, " +
            "and a partner's tricks count for your side exactly like your own.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.TEN of Suit.HEARTS,
        advice = "Nils leads the A♥ and you hold exactly one heart, so there is no decision " +
            "at all: the 10♥. Following the led suit is compulsory whenever you can do it.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.DIAMONDS,
        advice = "Diamonds now, and again you hold just one, so play the Q♦. Look at what " +
            "Bruno threw: the J♦. Only the two BLACK Jacks are special while spades are " +
            "trump — this red one is an ordinary diamond, and a Queen outranks a Jack.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.NINE of Suit.CLUBS,
        advice = "One card left, so no choice: the 9♣. Your side already has the three " +
            "tricks it needed — see whether Nils can collect all five.",
    ),
)

/**
 * Shown while a completed trick is held on the felt, keyed by trick number 1-5. In practice only
 * the tricks a BOT wins are ever held (winning one puts the lead straight back in your hands);
 * the rest are safety notes.
 */
private fun basicsTrickNotes(): Map<Int, String> = mapOf(
    1 to "Right bower over left: your J♠ beat Nils's J♣. Both of those Jacks were spades, " +
        "while the two clubs sitting in your hand were not eligible at all.",
    2 to "Kira's A♣ was winning — until Nils, holding no clubs, dropped the Q♠ on it. Any " +
        "trump beats any card of the led suit. Tap the trick to continue.",
    3 to "No trumps appeared, so the highest heart took it and Nils's A♥ was the highest. " +
        "That is three tricks to your side: the ♠ call is made. Tap the trick to continue.",
    4 to "Your Q♦ was the best diamond played — the J♦ counts for nothing outside its own " +
        "suit while spades are trump.",
    5 to "Nils's A♠ swept the last one. All five tricks to your side: that is a MARCH, worth " +
        "2 points instead of 1.",
)

/**
 * The pages read after the hand has been scored.
 */
private fun basicsEpilogue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "How a hand scores",
        body = "The side that made trump has to win at least three of the five tricks.\n\n" +
            "• 3 or 4 tricks: 1 point\n" +
            "• all 5 — a march: 2 points\n" +
            "• fewer than 3: the other side EUCHRES them and takes 2 points instead\n\n" +
            "Only one side ever scores in a hand, and the first to 10 wins the game.",
    ),
)
