// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.euchre.ui.tutorial

import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Seat
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.cardkit.ui.tutorial.TutorialPage

/**
 * LESSON 2 — making trump. Both bidding rounds, from the dealer's seat: pass on a turn card that
 * would help nobody, then name a different suit once it has been turned down — and learn that the
 * refused suit is the one suit round 2 may never name.
 *
 * The exact trace of seed 1 with the human (seat 0) dealing, every house rule off — generated by
 * `ai/src/jvmTest/.../TutorialTraceGenerator.kt`:
 *
 *   Bots: seat 1 = Hugo, seat 2 = Mira (your partner), seat 3 = Pia · YOU deal
 *   Turn card 9♥ · Hugo, Mira, Pia and you all pass · 9♥ turned down
 *   Round 2: Hugo, Mira, Pia pass · you name ♣ · trump ♣
 *   Your hand: J♣ J♠ 9♣ K♣ A♠
 *   1: Hugo A♦ · Mira 9♦ · Pia Q♦ · YOU 9♣    -> you (ruff)
 *   2: YOU J♣ · Hugo 10♦ · Mira Q♣ · Pia 9♠   -> you
 *   3: YOU J♠ · Hugo 10♥ · Mira A♣ · Pia 10♠  -> you (left bower over the ace)
 *   4: YOU A♠ · Hugo K♠ · Mira Q♥ · Pia J♥    -> you
 *   5: YOU K♣ · Hugo K♥ · Mira K♦ · Pia A♥    -> you
 *   All five: a march, +2.
 *
 * Do not edit a line of the prose without checking it against that trace.
 */
internal fun biddingLesson(): TutorialLesson = TutorialLesson(
    id = "bidding",
    ordinal = 2,
    title = "Making trump",
    subtitle = "Both bidding rounds, and the suit you may not name",
    seed = 1L,
    dealer = Seat(0),
    prologue = biddingPrologue(),
    steps = biddingSteps(),
    trickNotes = biddingTrickNotes(),
    handDone = "Your call is played out. See what naming clubs was worth.",
    epilogue = biddingEpilogue(),
    completion = "You passed on a turn card that suited nobody, named the suit your hand was " +
        "actually built for, and could not name hearts because the table had refused them. Then " +
        "you ruffed an ace, drew trumps with both bowers and took all five: a march, +2. Next " +
        "lesson: playing a hand alone.",
)

/**
 * The pages read before the hand is dealt.
 */
private fun biddingPrologue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "Where trump comes from",
        body = "Nobody chooses trump at random. After the deal, one card is turned face up " +
            "beside the undealt kitty, and the table is asked twice.\n\n" +
            "ROUND 1, starting left of the dealer: each player may ORDER UP the turned " +
            "card's suit as trump, or pass. If someone orders it up, the DEALER takes that " +
            "card into hand and buries one — so ordering up always hands the dealer's side " +
            "a known trump.",
    ),
    TutorialPage(
        title = "The second round",
        body = "If all four pass, the card is turned down and the table is asked again. Now " +
            "each player may name ANY suit as trump — any suit except the one just refused. " +
            "Nobody picks anything up this time; whoever names it simply becomes the MAKER, " +
            "and their side must win three of the five tricks or be euchred.\n\n" +
            "You deal this hand, so you speak last in both rounds. Watch what everyone else " +
            "does before you commit.",
    ),
)

/**
 * Every human decision of the lesson, in order. Grounded in the trace above — do not edit one
 * without the other.
 */
private fun biddingSteps(): List<EuchreTutorialStep> = listOf(
    EuchreTutorialStep.Round1Step(
        orderUp = false,
        advice = "Hugo, Mira and Pia have all passed, so it comes to you. You are the " +
            "dealer: ordering up means hearts are trump AND the 9♥ comes into your hand. " +
            "But count your hearts — you have none, and a lone 9 is no trump suit to build " +
            "on. Pass, and let the turn card go down.",
    ),
    EuchreTutorialStep.Round2Step(
        call = Suit.CLUBS,
        advice = "The 9♥ is turned down, everyone has passed again, and hearts are now the " +
            "one suit nobody may name. Look at clubs: the J♣ is the right bower, the J♠ " +
            "joins clubs as the left bower, and K♣ and 9♣ come with them — four trumps, the " +
            "top two of which cannot be beaten. Name ♣.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.NINE of Suit.CLUBS,
        advice = "Hugo leads the A♦ and you hold no diamonds at all, so you may play " +
            "anything — and any trump beats every diamond. Your smallest one is plenty: the " +
            "9♣ takes his ace. Trumping a suit you cannot follow is called a RUFF, and it is " +
            "why holding none of a suit is an asset, not a gap.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.JACK of Suit.CLUBS,
        advice = "You made trump, so pull the others' trumps out before they can ruff you. " +
            "Lead the J♣: with clubs trump it is the right bower and nothing in the deck " +
            "beats it.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.JACK of Suit.SPADES,
        advice = "Now the other Jack. The J♠ is a club for this hand — the LEFT BOWER, " +
            "second only to the right. Lead it, and watch Mira's A♣ fall underneath: in the " +
            "trump suit the two Jacks outrank the ace.",
        showBowerOrder = true,
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.ACE of Suit.SPADES,
        advice = "Three tricks: your ♣ call is already made, so everything from here is " +
            "profit. The trumps are gone, which means your plain-suit A♠ can no longer be " +
            "ruffed. Cash it.",
    ),
    EuchreTutorialStep.PlayStep(
        card = Rank.KING of Suit.CLUBS,
        advice = "Last card, and it is still a trump: the K♣ cannot be beaten by anything " +
            "left. That is all five tricks — a march.",
    ),
)

/**
 * Shown while a completed trick is held on the felt, keyed by trick number 1-5. In practice only
 * the tricks a BOT wins are ever held (winning one puts the lead straight back in your hands);
 * the rest are safety notes.
 */
private fun biddingTrickNotes(): Map<Int, String> = mapOf(
    1 to "Void in diamonds, so the little 9♣ was allowed to play — and it beat an ace. That " +
        "is a ruff.",
    2 to "The right bower took it, and Mira's Q♣ came out underneath — one fewer trump left " +
        "to ruff you with.",
    3 to "The left bower beat the ace of trumps: the last big club is gone, and so is every " +
        "trump but your own.",
    4 to "With every trump spent, the A♠ was simply the highest card of the suit led.",
    5 to "The K♣ finished the job: five tricks out of five for the maker. That is a march, " +
        "and it doubles the score to 2.",
)

/**
 * The pages read after the hand has been scored.
 */
private fun biddingEpilogue(): List<TutorialPage> = listOf(
    TutorialPage(
        title = "When to call",
        body = "A sound call needs about three tricks' worth of hand. Count them like " +
            "this: a bower is a trick, the ace of trumps is nearly one, and every extra " +
            "trump is worth something once the others have run out. A side-suit ace is " +
            "half a trick — it can be ruffed. Holding NONE of a suit is worth real value " +
            "too, because you can ruff it.\n\n" +
            "And remember who profits from round 1: ordering up puts the turn card in the " +
            "dealer's hand. Order up freely when you or your partner deals, and be much " +
            "more careful when an opponent does.",
    ),
)
