// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
import org.jetbrains.kotlin.gradle.tasks.Kotlin2JsCompile

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// TODO(KT-82989): see shared/build.gradle.kts. The Compose compiler plugin's top-level declarations
// break Kotlin JS/Wasm incremental compilation (KT-82395), silently shipping a stale wasm binary.
// The proper switch (Kotlin2JsCompile.incrementalJsKlib) is still `internal` (KT-82989), so wipe the
// IC state before each run to force a correct full compile. Drop this once KT-82989 ships.
tasks.withType<Kotlin2JsCompile>().configureEach {
    val icStateDir = layout.buildDirectory.dir("kotlin/$name")
    doFirst { icStateDir.get().asFile.deleteRecursively() }
}

// Generate a tiny AppBuildInfo with the app version from the single source (root gradle.properties),
// so the wasm build reports the same version the Android build does. (BuildConfig is Android-only.)
val generateAppVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/appVersion")
    val versionValue = providers.gradleProperty("appVersionName").get()
    // The short git commit this build was made from, surfaced in the app's about surface. Falls back
    // to "unknown" when git isn't available (e.g. a source-tarball build).
    val commitValue = runCatching {
        providers.exec { commandLine("git", "rev-parse", "--short=8", "HEAD") }
            .standardOutput.asText.get().trim()
    }.getOrNull()?.ifBlank { null } ?: "unknown"
    outputs.dir(outputDir)
    inputs.property("version", versionValue)
    inputs.property("commit", commitValue)
    doLast {
        val file = outputDir.get().file("AppBuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :web build.gradle.kts — do not edit.
            |package io.github.rotundtapir.euchre.web
            |
            |internal object AppBuildInfo {
            |    const val VERSION: String = "$versionValue"
            |    const val COMMIT: String = "$commitValue"
            |}
            |
            """.trimMargin(),
        )
    }
}

// The browser build: a Kotlin/Wasm executable around :shared's EuchreApp.
// `wasmJsBrowserDistribution` emits a static site (build/dist/wasmJs/productionExecutable)
// that GitHub Pages serves as-is; `wasmJsBrowserRun` serves it locally for development.
kotlin {
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "euchre.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        wasmJsMain {
            kotlin.srcDir(generateAppVersion)
            dependencies {
                implementation(project(":shared"))
                implementation(libs.kotlinx.browser)
                // For configureWebResources { }: resource URLs must stay relative to the page.
                implementation(compose.components.resources)
            }
        }
    }
}

compose.resources {
    packageOfResClass = "io.github.rotundtapir.euchre.web.generated.resources"
    // Resources live only in wasmJsMain (the fallback font); without this the Res class is
    // only generated for modules with commonMain resources.
    generateResClass = always
}
